CRITICAL - 2022-04-28 09:07:53 --> Class "App\Controllers\usuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:08:14 --> Class "App\Controllers\usuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:14:51 --> Class "App\Controllers\usuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:16:40 --> Class "App\Models\UsuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:16:43 --> Class "App\Models\UsuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:16:51 --> Class "App\Models\UsuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:20:19 --> Class "App\Controllers\usuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:20:31 --> Undefined property: App\Controllers\Login::$usuarioModel
#0 C:\ci4\app\Controllers\Login.php(15): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\ci4\\app\\Cont...', 15)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 09:22:33 --> Class "App\Models\UsuariosModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:22:46 --> Class "App\Models\usuariosModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:23:08 --> Class "App\Controllers\usuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:24:00 --> Class "App\Controllers\usuariosModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:24:14 --> Class "App\Controllers\UsuariosModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 09:25:14 --> Class "App\Controllers\UsuariosModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
ERROR - 2022-04-28 09:25:47 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:25:47 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:29:30 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:29:30 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:29:36 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:29:36 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:32:17 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:32:17 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
CRITICAL - 2022-04-28 09:38:54 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-04-28 09:40:01 --> Class CodeIgniter\Database\MySQLi\Connection contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (CodeIgniter\Database\BaseConnection::execute)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-04-28 09:40:06 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:40:06 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:40:36 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:40:36 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:40:38 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:40:38 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
CRITICAL - 2022-04-28 09:40:57 --> mysqli::query(): Passing null to parameter #2 ($result_mode) of type int is deprecated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8192, 'mysqli::query()...', 'C:\\ci4\\system\\D...', 292)
#1 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', NULL)
#2 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#4 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#8 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 09:41:05 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:41:05 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:43:20 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:43:20 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:43:21 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:43:21 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:43:28 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:43:28 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:47:26 --> mysqli_sql_exception: Table 'cadastro.users' doesn't exist in C:\ci4\system\Database\MySQLi\Connection.php:294
Stack trace:
#0 C:\ci4\system\Database\MySQLi\Connection.php(294): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
CRITICAL - 2022-04-28 09:47:26 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(294): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:47:28 --> mysqli_sql_exception: Table 'cadastro.users' doesn't exist in C:\ci4\system\Database\MySQLi\Connection.php:294
Stack trace:
#0 C:\ci4\system\Database\MySQLi\Connection.php(294): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
CRITICAL - 2022-04-28 09:47:28 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(294): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:47:46 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:47:46 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:47:58 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:47:58 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('dsad@fdsafdsa')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 09:49:27 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 09:49:27 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('dsad@fdsafdsa')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
CRITICAL - 2022-04-28 10:18:22 --> mysqli::query(): Passing null to parameter #2 ($result_mode) of type int is deprecated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8192, 'mysqli::query()...', 'C:\\ci4\\system\\D...', 292)
#1 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', NULL)
#2 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#4 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#8 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('dsad@fdsafdsa')
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 10:26:16 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 10:26:16 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('dsad@fdsafdsa')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 10:27:14 --> Table 'cadastro.users' doesn't exist
CRITICAL - 2022-04-28 10:27:14 --> Table 'cadastro.users' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...')
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('dsad@fdsafdsa')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 10:53:47 --> Table 'cadastro.cadastro' doesn't exist
CRITICAL - 2022-04-28 10:53:47 --> Table 'cadastro.cadastro' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
ERROR - 2022-04-28 11:01:25 --> Error connecting to the database: Unknown database 'usuarios'
CRITICAL - 2022-04-28 11:01:25 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'usuarios'
#0 C:\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#5 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#6 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#7 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#11 {main}
ERROR - 2022-04-28 11:01:58 --> Error connecting to the database: Unknown database 'codeigniter'
CRITICAL - 2022-04-28 11:01:58 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'codeigniter'
#0 C:\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\ci4\app\Models\usuarioModel.php(16): CodeIgniter\BaseModel->first()
#5 C:\ci4\app\Controllers\Login.php(18): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#6 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#7 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#10 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#11 {main}
CRITICAL - 2022-04-28 11:11:31 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:12:20 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(20): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:12:21 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(20): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:12:22 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(20): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:12:30 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:13:29 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:13:29 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:13:33 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:13:33 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:13:56 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:13:57 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:14:16 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:18:56 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:18:58 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:18:58 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:18:58 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 11:18:59 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
ERROR - 2022-04-28 11:27:26 --> Table 'cadastro.cadastro' doesn't exist
CRITICAL - 2022-04-28 11:27:26 --> Table 'cadastro.cadastro' doesn't exist
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\ci4\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\ci4\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\ci4\app\Models\usuarioModel.php(25): CodeIgniter\BaseModel->first()
#7 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail('admin@admin.com')
#8 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#9 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#13 {main}
CRITICAL - 2022-04-28 12:14:01 --> Call to undefined method CodeIgniter\Session\Session::isLogged()
#0 C:\ci4\system\Filters\Filters.php(173): App\Filters\Auth->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#1 C:\ci4\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('/', 'before')
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 12:14:02 --> Call to undefined method CodeIgniter\Session\Session::isLogged()
#0 C:\ci4\system\Filters\Filters.php(173): App\Filters\Auth->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#1 C:\ci4\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('/', 'before')
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 12:14:21 --> Call to undefined method CodeIgniter\Session\Session::isLogged()
#0 C:\ci4\system\Filters\Filters.php(173): App\Filters\Auth->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#1 C:\ci4\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('/', 'before')
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 12:16:41 --> Call to undefined method CodeIgniter\Session\Session::UsuarioLogado()
#0 C:\ci4\system\Filters\Filters.php(173): App\Filters\Auth->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#1 C:\ci4\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('login', 'before')
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 12:16:42 --> Call to undefined method CodeIgniter\Session\Session::UsuarioLogado()
#0 C:\ci4\system\Filters\Filters.php(173): App\Filters\Auth->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#1 C:\ci4\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('login', 'before')
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 12:19:15 --> Unclosed '{' on line 13 does not match ']'
#0 C:\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\ci4\\app\\Conf...')
#1 C:\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Filters')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Filters')
#3 C:\ci4\system\Config\Factories.php(136): class_exists('Config\\Filters')
#4 C:\ci4\system\Config\Factories.php(106): CodeIgniter\Config\Factories::locateClass(Array, 'Filters')
#5 C:\ci4\system\Common.php(198): CodeIgniter\Config\Factories::__callStatic('config', Array)
#6 C:\ci4\system\Config\Services.php(258): config('Filters')
#7 C:\ci4\system\Config\BaseService.php(248): CodeIgniter\Config\Services::filters(NULL, false)
#8 C:\ci4\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('filters', Array)
#9 C:\ci4\system\Config\Services.php(255): CodeIgniter\Config\BaseService::getSharedInstance('filters', NULL)
#10 C:\ci4\system\Config\BaseService.php(248): CodeIgniter\Config\Services::filters()
#11 C:\ci4\system\CodeIgniter.php(373): CodeIgniter\Config\BaseService::__callStatic('filters', Array)
#12 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#15 {main}
CRITICAL - 2022-04-28 12:19:16 --> Unclosed '{' on line 13 does not match ']'
#0 C:\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\ci4\\app\\Conf...')
#1 C:\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Filters')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Filters')
#3 C:\ci4\system\Config\Factories.php(136): class_exists('Config\\Filters')
#4 C:\ci4\system\Config\Factories.php(106): CodeIgniter\Config\Factories::locateClass(Array, 'Filters')
#5 C:\ci4\system\Common.php(198): CodeIgniter\Config\Factories::__callStatic('config', Array)
#6 C:\ci4\system\Config\Services.php(258): config('Filters')
#7 C:\ci4\system\Config\BaseService.php(248): CodeIgniter\Config\Services::filters(NULL, false)
#8 C:\ci4\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('filters', Array)
#9 C:\ci4\system\Config\Services.php(255): CodeIgniter\Config\BaseService::getSharedInstance('filters', NULL)
#10 C:\ci4\system\Config\BaseService.php(248): CodeIgniter\Config\Services::filters()
#11 C:\ci4\system\CodeIgniter.php(373): CodeIgniter\Config\BaseService::__callStatic('filters', Array)
#12 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#15 {main}
CRITICAL - 2022-04-28 12:31:43 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 12:31:59 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 12:32:26 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(20): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 12:36:06 --> syntax error, unexpected token "public", expecting end of file
#0 C:\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\ci4\\app\\Filt...')
#1 C:\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Filters\\Aut...')
#2 C:\ci4\system\Filters\Filters.php(166): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Filters\\Aut...')
#3 C:\ci4\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('login', 'before')
#4 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#7 {main}
CRITICAL - 2022-04-28 12:36:07 --> syntax error, unexpected token "public", expecting end of file
#0 C:\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\ci4\\app\\Filt...')
#1 C:\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Filters\\Aut...')
#2 C:\ci4\system\Filters\Filters.php(166): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Filters\\Aut...')
#3 C:\ci4\system\CodeIgniter.php(393): CodeIgniter\Filters\Filters->run('login', 'before')
#4 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#7 {main}
CRITICAL - 2022-04-28 13:40:22 --> Invalid file: users.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('users.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#2 C:\ci4\app\Controllers\User.php(19): view('users', Array)
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 13:54:40 --> Invalid file: users.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('users.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#2 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 13:54:57 --> Class "App\Controllers\UserModel" not found
#0 C:\ci4\system\CodeIgniter.php(809): App\Controllers\User->__construct()
#1 C:\ci4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 13:54:58 --> Class "App\Controllers\UserModel" not found
#0 C:\ci4\system\CodeIgniter.php(809): App\Controllers\User->__construct()
#1 C:\ci4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 13:55:02 --> Invalid file: users.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('users.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#2 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 13:55:33 --> Class "App\Controllers\UserModel" not found
#0 C:\ci4\system\CodeIgniter.php(809): App\Controllers\User->__construct()
#1 C:\ci4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 13:55:34 --> Class "App\Controllers\UserModel" not found
#0 C:\ci4\system\CodeIgniter.php(809): App\Controllers\User->__construct()
#1 C:\ci4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 13:55:37 --> Undefined array key "name"
#0 C:\ci4\app\Views\users.php(55): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\ci4\\app\\View...', 55)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#4 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 13:55:38 --> Undefined array key "name"
#0 C:\ci4\app\Views\users.php(55): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\ci4\\app\\View...', 55)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#4 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 13:55:51 --> Undefined variable $pager
#0 C:\ci4\app\Views\users.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 65)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#4 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 13:55:52 --> Undefined variable $pager
#0 C:\ci4\app\Views\users.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 65)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#4 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:00:32 --> Undefined variable $pager
#0 C:\ci4\app\Views\users.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 65)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#4 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:00:33 --> Undefined variable $pager
#0 C:\ci4\app\Views\users.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 65)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('users', Array, true)
#4 C:\ci4\app\Controllers\User.php(17): view('users', Array)
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->index()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:24:37 --> Invalid file: success.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('success.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('success', Array, true)
#2 C:\ci4\app\Controllers\User.php(24): view('success', Array)
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->delete('10')
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 14:25:03 --> Invalid file: success.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('success.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('success', Array, true)
#2 C:\ci4\app\Controllers\User.php(24): view('success', Array)
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->delete('8')
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 14:26:09 --> Invalid file: success.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('success.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('success', Array, true)
#2 C:\ci4\app\Controllers\User.php(24): view('success', Array)
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->delete('11')
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 14:26:57 --> Invalid file: success.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('success.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('success', Array, true)
#2 C:\ci4\app\Controllers\User.php(24): view('success', Array)
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->delete('13')
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 14:47:18 --> Invalid file: create.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('create.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('create', Array, true)
#2 C:\ci4\app\Controllers\User.php(34): view('create')
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 14:47:41 --> Invalid file: form.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('form.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#2 C:\ci4\app\Controllers\User.php(34): view('form')
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 14:48:18 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('formulario')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:49:20 --> Invalid file: formulario.php
#0 C:\ci4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('formulario.php')
#1 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#2 C:\ci4\app\Controllers\User.php(34): view('formulario')
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 14:49:37 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('form')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:50:21 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('formulario')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:50:22 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('formulario')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:50:24 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('formulario')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:51:05 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('formulario')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:51:07 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('formulario')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:51:17 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('formulario', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('formulario')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:52:15 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('form')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:52:17 --> Call to undefined function form_open()
#0 C:\ci4\system\View\View.php(210): include()
#1 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#3 C:\ci4\app\Controllers\User.php(34): view('form')
#4 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#5 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#9 {main}
CRITICAL - 2022-04-28 14:52:35 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:52:36 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:52:54 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:52:56 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:53:12 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:53:36 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:53:49 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:53:58 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:56:17 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:58:18 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:59:04 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:59:05 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:59:11 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 14:59:12 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 15:02:29 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 15:03:39 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 14)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 15:10:59 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 13)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 15:10:59 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 13)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
CRITICAL - 2022-04-28 15:11:00 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(13): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 13)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
ERROR - 2022-04-28 15:19:41 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:19:41 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(43): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:20:40 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:20:40 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:23:54 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:23:54 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:24:47 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:24:47 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:27:09 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:27:09 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(34): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:27:15 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:27:15 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(38): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:27:17 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:27:17 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(38): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:28:19 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:28:19 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(44): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:28:22 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:28:22 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(44): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:28:25 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:28:25 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(44): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:28:39 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:28:39 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(38): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:31:54 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:31:54 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(42): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:52:49 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:52:49 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:54:16 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:54:16 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:54:53 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:54:53 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:55:04 --> Unknown column 'name' in 'field list'
CRITICAL - 2022-04-28 15:55:04 --> Unknown column 'name' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:55:56 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:55:56 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 15:58:43 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 15:58:43 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 16:00:49 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 16:00:49 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
CRITICAL - 2022-04-28 16:01:12 --> Undefined variable $user
#0 C:\ci4\app\Views\form.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\View...', 16)
#1 C:\ci4\system\View\View.php(210): include('C:\\ci4\\app\\View...')
#2 C:\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\ci4\system\Common.php(1089): CodeIgniter\View\View->render('form', Array, true)
#4 C:\ci4\app\Controllers\User.php(34): view('form')
#5 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->create()
#6 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#10 {main}
ERROR - 2022-04-28 16:04:09 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 16:04:09 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 16:05:02 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 16:05:02 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
CRITICAL - 2022-04-28 16:22:25 --> Undefined property: App\Controllers\Login::$userModel
#0 C:\ci4\app\Controllers\Login.php(10): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\ci4\\app\\Cont...', 10)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->index()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 16:22:26 --> Undefined property: App\Controllers\Login::$userModel
#0 C:\ci4\app\Controllers\Login.php(10): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\ci4\\app\\Cont...', 10)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->index()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 16:22:27 --> Undefined property: App\Controllers\Login::$userModel
#0 C:\ci4\app\Controllers\Login.php(10): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\ci4\\app\\Cont...', 10)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->index()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 16:23:09 --> Undefined property: App\Controllers\Login::$userModel
#0 C:\ci4\app\Controllers\Login.php(10): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\ci4\\app\\Cont...', 10)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->index()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 16:23:10 --> Undefined property: App\Controllers\Login::$userModel
#0 C:\ci4\app\Controllers\Login.php(10): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\ci4\\app\\Cont...', 10)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->index()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 16:23:13 --> syntax error, unexpected token "}", expecting ";"
#0 C:\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('login')
#1 C:\ci4\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('login')
#2 C:\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 16:23:14 --> syntax error, unexpected token "}", expecting ";"
#0 C:\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('login')
#1 C:\ci4\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('login')
#2 C:\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 16:23:15 --> syntax error, unexpected token "}", expecting ";"
#0 C:\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('login')
#1 C:\ci4\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('login')
#2 C:\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 17:46:00 --> Unclosed '{' on line 8
#0 C:\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\ci4\\app\\Mode...')
#1 C:\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Usua...')
#2 C:\ci4\app\Controllers\Login.php(18): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Usua...')
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 17:47:59 --> Unclosed '{' on line 7
#0 C:\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\ci4\\app\\Mode...')
#1 C:\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Usua...')
#2 C:\ci4\app\Controllers\Login.php(18): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Usua...')
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 17:48:04 --> Unclosed '{' on line 7
#0 C:\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\ci4\\app\\Mode...')
#1 C:\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Usua...')
#2 C:\ci4\app\Controllers\Login.php(18): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Usua...')
#3 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#4 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#5 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#8 {main}
CRITICAL - 2022-04-28 17:48:18 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(19): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 17:51:09 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 19
#0 C:\ci4\app\Controllers\Login.php(19): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 17:52:06 --> Class "App\Models\UsuarioModel" not found
#0 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#1 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#2 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#5 {main}
CRITICAL - 2022-04-28 17:52:42 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(19): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:05:48 --> Undefined array key "senha"
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:06:33 --> Undefined array key "email"
#0 C:\ci4\app\Controllers\Login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\ci4\\app\\Cont...', 23)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:06:34 --> Undefined array key "email"
#0 C:\ci4\app\Controllers\Login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\ci4\\app\\Cont...', 23)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:06:39 --> Undefined array key "email"
#0 C:\ci4\app\Controllers\Login.php(23): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\ci4\\app\\Cont...', 23)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:24:12 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:24:36 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:24:37 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:24:49 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:25:22 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:25:23 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:25:43 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:25:44 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:25:59 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:26:22 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:26:22 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:27:18 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:27:19 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:27:40 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 18:27:59 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
ERROR - 2022-04-28 21:46:45 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-04-28 21:46:45 --> Unknown column 'updated_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `usuario...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\ci4\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\ci4\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#5 C:\ci4\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\ci4\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\ci4\system\BaseModel.php(656): CodeIgniter\Model->update('28', Array)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 21:46:59 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 21:46:59 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
CRITICAL - 2022-04-28 21:51:53 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
ERROR - 2022-04-28 22:09:28 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 22:09:28 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 22:18:00 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 22:18:00 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 22:19:00 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 22:19:00 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(39): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 22:19:09 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 22:19:09 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(39): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 22:20:43 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-04-28 22:20:43 --> Unknown column 'created_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\ci4\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\ci4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\ci4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\ci4\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\ci4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 22:23:42 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-04-28 22:23:42 --> Unknown column 'updated_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `usuario...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\ci4\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\ci4\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#5 C:\ci4\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\ci4\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\ci4\system\BaseModel.php(656): CodeIgniter\Model->update('22', Array)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 22:24:53 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-04-28 22:24:53 --> Unknown column 'updated_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `usuario...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\ci4\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\ci4\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#5 C:\ci4\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\ci4\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\ci4\system\BaseModel.php(656): CodeIgniter\Model->update('22', Array)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
ERROR - 2022-04-28 22:24:56 --> Unknown column 'updated_at' in 'field list'
CRITICAL - 2022-04-28 22:24:56 --> Unknown column 'updated_at' in 'field list'
#0 C:\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `usuario...', 0)
#1 C:\ci4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\ci4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\ci4\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\ci4\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#5 C:\ci4\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\ci4\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\ci4\system\BaseModel.php(656): CodeIgniter\Model->update('22', Array)
#8 C:\ci4\app\Controllers\User.php(37): CodeIgniter\BaseModel->save(Array)
#9 C:\ci4\system\CodeIgniter.php(832): App\Controllers\User->store()
#10 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#14 {main}
CRITICAL - 2022-04-28 22:27:38 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:28:51 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:29:35 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:29:36 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:30:19 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:30:20 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:30:28 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:30:36 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:32:10 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:32:37 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:32:37 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:32:57 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:32:58 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:33:10 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:33:11 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:35:31 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:35:32 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:35:45 --> Call to undefined method App\Models\UsuarioModel::getByEmail
#0 C:\ci4\app\Controllers\Login.php(20): CodeIgniter\Model->__call('getByEmail', Array)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:37:28 --> Undefined variable $dadosUsuario
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:38:18 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:40:38 --> syntax error, unexpected token "public"
#0 C:\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('login')
#1 C:\ci4\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('login')
#2 C:\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:42:54 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:43:13 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:44:17 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:44:37 --> App\Models\UsuarioModel::getByEmail(): Argument #1 ($email) must be of type string, null given, called in C:\ci4\app\Controllers\Login.php on line 20
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:44:56 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:45:09 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:45:49 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:45:59 --> Trying to access array offset on value of type null
#0 C:\ci4\app\Controllers\Login.php(22): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', 'C:\\ci4\\app\\Cont...', 22)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:46:07 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 22:47:02 --> count(): Argument #1 ($value) must be of type Countable|array, null given
#0 C:\ci4\app\Controllers\Login.php(22): count(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
CRITICAL - 2022-04-28 23:15:21 --> App\Models\UsuarioModel::getByEmail(): Return value must be of type array, null returned
#0 C:\ci4\app\Controllers\Login.php(20): App\Models\UsuarioModel->getByEmail(NULL)
#1 C:\ci4\system\CodeIgniter.php(832): App\Controllers\Login->signIn()
#2 C:\ci4\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#3 C:\ci4\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\ci4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\ci4\\public\\i...')
#6 {main}
